project:
  type: website
  output-dir: docs

website:
  title: "Marc Wenzlawski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test.ipynb

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



