project:
  type: website
  output-dir: docs

website:
  title: "Marc Wenzlawski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        href: https://wenzlawski.github.io/blog

format:
  html:
    theme: 
      light: simplex
      dark: cyborg
    css: styles.scss
    toc: true



